### 东方财富-概念板块
接口: stock_board_concept_name_em
目标地址: https://quote.eastmoney.com/center/boardlist.html#concept_board
描述: 东方财富网-行情中心-沪深京板块-概念板块
限量: 单次返回当前时刻所有概念板块的实时行情数据

In [1]:
import akshare as ak

stock_board_concept_name_em_df = ak.stock_board_concept_name_em()
stock_board_concept_name_em_df

  0%|          | 0/4 [00:00<?, ?it/s]

,排名,板块名称,板块代码,最新价,涨跌额,涨跌幅,总市值,换手率,上涨家数,下跌家数,领涨股票,领涨股票-涨跌幅
0,1,昨日打二板以上表现,BK1645,5812.82,361.03,6.62,57048390000,15.37,2,1,兴业科技,10.00
1,2,昨日连板_含一字,BK1051,23726.12,720.04,3.13,710626656000,14.53,12,5,兴业科技,10.00
2,3,玻璃基板,BK1175,3604.77,62.87,1.78,1763894576000,11.40,21,20,雷曼光电,19.98
3,4,昨日连板,BK0816,17623.70,292.12,1.69,629117008000,13.40,8,5,超声电子,10.01
4,5,工业气体,BK0981,3256.67,49.15,1.53,967344400000,4.08,13,16,航天工程,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...
489,490,2026一季报扭亏,BK1682,1257.44,-63.28,-4.79,717740384000,5.19,1,10,德明利,6.73
490,491,同步磁阻电机,BK1131,2143.30,-108.12,-4.80,97806477000,4.38,0,7,佳电股份,-1.34
491,492,Kimi概念,BK1169,991.41,-51.25,-4.92,406689088000,3.66,1,15,ST信源,0.75
492,493,CPO概念,BK1128,10784.45,-612.80,-5.38,7869676800000,6.55,7,49,乾照光电,9.84
493,494,锂矿概念,BK1173,2005.16,-124.26,-5.84,3877201488000,2.94,2,35,怡 亚 通,2.36

In [2]:
stock_board_concept_name_em_df.to_csv('东方财富-概念板块-实时行情.csv')

### 东方财富-概念板块-实时行情
接口: stock_board_concept_spot_em

目标地址: https://quote.eastmoney.com/bk/90.BK0818.html

描述: 东方财富网-行情中心-沪深京板块-概念板块-实时行情

限量: 单次返回指定概念板块的实时行情数据

In [2]:
import akshare as ak

stock_board_concept_spot_em_df = ak.stock_board_concept_spot_em(symbol="重组蛋白")
stock_board_concept_spot_em_df

  0%|          | 0/4 [00:00<?, ?it/s]

  item         value
0   最新  1.225660e+03
1   最高  1.238100e+03
2   最低  1.202360e+03
3   开盘  1.214300e+03
4  成交量  2.562854e+06
5  成交额  6.720262e+09
6  换手率  3.500000e+00
7  涨跌额  1.316000e+01
8  涨跌幅  1.090000e+00
9   振幅  2.950000e+00

### 东方财富-成份股

接口: stock_board_concept_cons_em

目标地址: http://quote.eastmoney.com/center/boardlist.html#boards-BK06551

描述: 东方财富-沪深板块-概念板块-板块成份

限量: 单次返回当前时刻所有成份股

In [3]:
import akshare as ak

stock_board_concept_cons_em_df = ak.stock_board_concept_cons_em(symbol="创新药")
stock_board_concept_cons_em_df

  0%|          | 0/1 [00:00<?, ?it/s]

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,最低,今开,昨收,换手率,市盈率-动态,市净率
0,1,688506,百利天恒,410.00,13.39,48.42,21650,8.122573e+08,16.79,411.00,350.28,359.78,361.58,2.10,-73.53,58.74
1,2,002020,京新药业,20.45,6.45,1.24,427246,8.606468e+08,8.22,20.78,19.20,19.20,19.21,5.90,22.70,3.22
2,3,688658,悦康药业,29.70,6.38,1.78,118351,3.600508e+08,10.32,31.69,28.81,28.81,27.92,2.63,-67.62,3.84
3,4,600211,西藏药业,49.79,5.98,2.81,246249,1.238259e+09,8.45,51.68,47.71,47.71,46.98,7.64,14.14,3.86
4,5,688382,益方生物-U,43.06,5.36,2.19,150751,6.463475e+08,8.74,43.97,40.40,40.84,40.87,3.61,-104.25,14.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,141,688189,南新制药,14.88,-3.50,-0.54,149888,2.250800e+08,5.51,15.55,14.70,15.00,15.42,5.46,-51.04,4.56
141,142,000766,通化金马,23.25,-3.53,-0.85,257794,6.119895e+08,4.90,24.25,23.07,24.03,24.10,2.67,668.62,9.89
142,143,600222,太龙药业,6.72,-4.00,-0.28,294423,2.029408e+08,6.86,7.18,6.70,6.99,7.00,5.13,99.67,2.41
143,144,300158,振东制药,8.21,-4.53,-0.39,675188,5.637394e+08,6.16,8.65,8.12,8.56,8.60,6.72,520.32,2.26
144,145,300199,翰宇药业,25.36,-5.02,-1.34,687623,1.789769e+09,6.59,27.04,25.28,26.50,26.70,9.22,76.99,30.95

### 东方财富-行业板块
接口: stock_board_industry_name_em

目标地址: https://quote.eastmoney.com/center/boardlist.html#industry_board

描述: 东方财富-沪深京板块-行业板块

限量: 单次返回当前时刻所有行业板的实时行情数据

In [4]:
import akshare as ak

stock_board_industry_name_em_df = ak.stock_board_industry_name_em()
stock_board_industry_name_em_df

  0%|          | 0/4 [00:00<?, ?it/s]

,排名,板块名称,板块代码,最新价,涨跌额,涨跌幅,总市值,换手率,上涨家数,下跌家数,领涨股票,领涨股票-涨跌幅
0,1,橡胶助剂,BK1443,5454.94,280.11,5.41,58288026000,5.54,2,0,彤程新材,10.00
1,2,有机硅,BK1431,3919.72,176.52,4.72,134980965000,5.64,8,2,晨光新材,10.02
2,3,硅料硅片,BK1319,2040.40,83.71,4.28,102218825000,7.56,3,2,双良节能,10.00
3,4,航天装备Ⅱ,BK1232,5340.60,217.96,4.25,449676064000,5.02,7,2,中国卫星,10.00
4,5,航天装备Ⅲ,BK1385,5340.60,217.96,4.25,449676064000,5.02,7,2,中国卫星,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...
491,492,镍,BK1622,5592.88,-408.80,-6.81,88747879000,3.68,0,1,华友钴业,-6.81
492,493,期货,BK1361,487.78,-36.44,-6.95,48278900000,1.60,0,4,永安期货,-5.22
493,494,能源金属,BK1015,969.17,-82.15,-7.81,507381280000,6.13,0,11,寒锐钴业,-5.49
494,495,通信线缆及配套,BK1592,33261.22,-2924.61,-8.08,1192686192000,10.14,0,13,富士达,-0.74
495,496,锂,BK1621,18196.79,-1642.09,-8.28,387549104000,7.11,0,8,永兴材料,-6.53

In [5]:
stock_board_industry_name_em_df.to_csv('东方财富-行业板块-实时行情.csv')

### 东方财富-行业板块-实时行情
接口: stock_board_industry_spot_em

目标地址: https://quote.eastmoney.com/bk/90.BK1027.html

描述: 东方财富网-沪深板块-行业板块-实时行情

限量: 单次返回指定板块的实时行情数据

In [5]:
import akshare as ak

stock_board_industry_spot_em_df = ak.stock_board_industry_spot_em(symbol="小金属")
stock_board_industry_spot_em_df

0it [00:00, ?it/s]

  item         value
0   最新  3.062380e+03
1   最高  3.197950e+03
2   最低  3.047380e+03
3   开盘  3.191780e+03
4  成交量  2.334431e+07
5  成交额  6.274191e+10
6  换手率  4.970000e+00
7  涨跌额 -1.195700e+02
8  涨跌幅 -3.760000e+00
9   振幅  4.730000e+00

### 东方财富-成份股
接口: stock_board_industry_cons_em

目标地址: https://data.eastmoney.com/bkzj/BK1027.html

描述: 东方财富-沪深板块-行业板块-板块成份

限量: 单次返回指定 symbol 的所有成份股

In [6]:
import akshare as ak

stock_board_industry_cons_em_df = ak.stock_board_industry_cons_em(symbol="贵金属")
stock_board_industry_cons_em_df

0it [00:00, ?it/s]

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,最低,今开,昨收,换手率,市盈率-动态,市净率
0,1,601069,西部黄金,26.51,10.00,2.41,714953,1.867444e+09,6.27,26.51,25.00,25.40,24.10,10.45,78.63,5.01
1,2,000506,招金黄金,10.49,6.93,0.68,630020,6.482288e+08,7.14,10.65,9.95,10.06,9.81,6.78,109.02,15.84
2,3,600489,中金黄金,18.17,2.31,0.41,1947576,3.565643e+09,4.62,18.75,17.93,18.53,17.76,4.02,16.34,3.11
3,4,600547,山东黄金,36.70,2.20,0.79,587382,2.162698e+09,4.34,37.66,36.10,37.35,35.91,1.63,29.23,6.15
4,5,600988,赤峰黄金,28.02,0.76,0.21,960782,2.743466e+09,6.01,29.37,27.70,28.87,27.81,5.77,24.05,4.59
5,6,000975,山金国际,20.74,0.48,0.10,431617,9.078315e+08,5.77,21.63,20.44,21.24,20.64,1.71,18.04,4.24
6,7,002237,恒邦股份,13.24,0.46,0.06,399943,5.335593e+08,4.40,13.69,13.11,13.47,13.18,4.39,24.60,1.59
7,8,001337,四川黄金,25.81,-0.88,-0.23,259656,6.806294e+08,5.34,26.95,25.56,26.75,26.04,9.00,25.98,6.89
8,9,002155,湖南黄金,22.09,-0.90,-0.20,1091804,2.442004e+09,8.66,23.43,21.50,23.27,22.29,6.99,26.32,4.73
9,10,300139,晓程科技,22.05,-3.46,-0.79,793822,1.812037e+09,9.28,23.95,21.83,23.88,22.84,33.97,71.16,5.70
10,11,002716,湖南白银,6.00,-5.21,-0.33,2746448,1.688429e+09,8.06,6.42,5.91,6.39,6.33,12.42,136.17,5.04

### 板块异动详情
接口: stock_board_change_em

目标地址: https://quote.eastmoney.com/changes/

描述: 东方财富-行情中心-当日板块异动详情

限量: 返回最近交易日的数据

In [8]:
import akshare as ak

stock_board_change_em_df = ak.stock_board_change_em()
stock_board_change_em_df

,板块名称,涨跌幅,主力净流入,板块异动总次数,板块异动最频繁个股及所属类型-股票代码,板块异动最频繁个股及所属类型-股票名称,板块异动最频繁个股及所属类型-买卖方向,板块具体异动类型列表及出现次数
0,融资融券,2.70,4.407903e+06,11111,603370,N华新,大笔卖出,"[{'t': 8201, 'ct': 2098}, {'t': 8193, 'ct': 20..."
1,深股通,2.76,2.653976e+06,4551,301590,优优绿能,大笔买入,"[{'t': 128, 'ct': 872}, {'t': 8201, 'ct': 818}..."
2,专精特新,3.41,5.238409e+05,4064,603370,N华新,大笔卖出,"[{'t': 8193, 'ct': 1032}, {'t': 8201, 'ct': 89..."
3,创业板综,3.01,1.442941e+06,3741,301590,优优绿能,大笔买入,"[{'t': 8193, 'ct': 929}, {'t': 8201, 'ct': 818..."
4,沪股通,2.20,1.518130e+06,3065,600246,万通发展,大笔卖出,"[{'t': 8201, 'ct': 650}, {'t': 128, 'ct': 464}..."
...,...,...,...,...,...,...,...,...
548,净水概念,1.45,3.587025e+04,4,000651,格力电器,大笔买入,"[{'t': 64, 'ct': 3}, {'t': 8215, 'ct': 1}]"
549,气溶胶检测,2.13,1.057016e+04,3,300203,聚光科技,大笔买入,"[{'t': 8201, 'ct': 3}]"
550,可燃冰,1.08,6.457051e+03,2,603699,纽威股份,大笔卖出,"[{'t': 8201, 'ct': 1}, {'t': 8202, 'ct': 1}]"
551,多元金融,1.27,2.677467e+04,1,002423,中粮资本,大笔买入,"[{'t': 8201, 'ct': 1}]"
552,低碳冶金,0.54,1.036058e+03,1,000928,中钢国际,大笔买入,"[{'t': 128, 'ct': 1}]"